version: "3.9"
services:
  exchange-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql