spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    port: 5432
    database-name: exchangedb
    username: exchangeuser
    password: exchangepass
    url: jdbc:postgresql://localhost:${spring.datasource.port}/${spring.datasource.database-name}
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
server:
  port: 8000
  servlet:
    context-path: /api
jwt:
  secret: 4529482B4D6251655468576D5A7134743777217A25432A462D4A614E63526655
  time-to-expire: 86400000